# Generated by Django 3.2.6 on 2021-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_create_at_endpoint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at'),
        ),
    ]
