# Generated by Django 3.2.6 on 2021-08-04 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210804_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f994ba77-875e-49c6-be35-a2ccd70a846c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0d0d2c66-dfc2-4363-bb4b-1fd51fd00ae3'), verbose_name='Slug'),
        ),
    ]
