# Generated by Django 3.2.6 on 2021-08-09 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210809_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d51d8048-be74-4f57-8f83-2ff724298a8c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a79b147e-fb5a-4cae-b349-8f989342f8cf'), verbose_name='Slug'),
        ),
    ]
