# Generated by Django 3.2.6 on 2021-08-09 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210809_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0746b2c5-cc4e-48cc-af53-a81a14e6c84d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7d10181c-54bd-4fee-bdff-e03a762351b5'), verbose_name='Slug'),
        ),
    ]
