# Generated by Django 3.2.6 on 2021-08-09 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210809_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a5c7ca2f-0589-4e0d-af83-dfb97df7ad15'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8806eafb-2cba-40b4-9bf0-fea8c75e0cef'), verbose_name='Slug'),
        ),
    ]
