# Generated by Django 3.2.6 on 2021-08-11 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210811_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a60a4830-b8d4-48eb-9b76-d56f2546c6ca'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d7583b38-3540-40ec-976d-929b5b76dadb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5a14f2c3-8856-418a-9508-91bde80ba7be'), verbose_name='Slug'),
        ),
    ]
