# Generated by Django 3.2.6 on 2021-08-11 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210811_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('591d2b46-7bca-4f82-b0b4-a9c276fdcd3a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('606a7d24-438f-44aa-807f-876b66454838'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fb2e2aa3-5b8b-437a-8fee-9926e31e132f'), verbose_name='Slug'),
        ),
    ]
