# Generated by Django 3.2.6 on 2021-08-11 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210811_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e0658df6-c5b4-401c-8df5-ca1c14744b31'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ed8e261b-972a-431c-bc8f-99112bb447c7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8ccf2a1b-c6cd-4dae-87fc-183a73d70427'), verbose_name='Slug'),
        ),
    ]
