# Generated by Django 3.2.6 on 2021-08-11 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210811_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('94c31319-4f81-424f-a75c-2602116d2e25'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('30784fdb-49e6-4f05-8fbe-f0e94878909d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8bf6f79a-e5c1-475f-8503-a3fea6eea236'), verbose_name='Slug'),
        ),
    ]
