# Generated by Django 3.2.6 on 2021-08-11 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210811_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a29abe73-9bfb-45e5-abe1-3221c0287625'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e0dbe99b-acc6-4011-bcb0-440bfd447e4f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c6c91114-b1da-444f-b2f9-5435c8143391'), verbose_name='Slug'),
        ),
    ]
