# Generated by Django 3.2.6 on 2021-08-11 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210811_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e056f410-4657-4334-8d39-dd41a87cde14'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6011808c-0df0-4f53-8d82-b7455dc7393e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5e8cbb09-d442-4cc9-ae61-686d1379d158'), verbose_name='Slug'),
        ),
    ]
