# Generated by Django 3.2.6 on 2021-08-11 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210811_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4614de83-7485-479e-a21d-70b156eaf5b8'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('59f0f8d2-8172-4b9c-a460-7c1a4a07a3a4'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3d8b5824-a6c0-473a-a446-11c1c26e3c98'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
