# Generated by Django 3.2.6 on 2021-08-11 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210811_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a0671453-45ca-4250-9ecb-8c5402a99c6c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9aa75a4a-d43d-4166-8d1f-cf8b1bf395f0'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5acafe9e-f9f2-436f-9db3-1b66a8b01596'), verbose_name='Slug'),
        ),
    ]
