# Generated by Django 3.2.6 on 2021-08-11 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210811_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bfc80762-2682-48c0-b699-8ec78bfd824c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a43d596b-d631-4aa9-bd48-9a4d2bd87496'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d3b50c73-1c2e-468c-a202-bc7097e93f78'), verbose_name='Slug'),
        ),
    ]
