# Generated by Django 3.2.6 on 2021-08-11 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210811_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bbb50807-8373-497d-8961-d05994c8dea8'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f9e1bf27-17ed-4ec8-9af8-b22307a4025d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('75efaf00-3392-46e0-9748-bdb0e9612ba6'), verbose_name='Slug'),
        ),
    ]
