# Generated by Django 3.2.6 on 2021-08-11 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210811_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5b02cfda-b74e-4034-82cd-9366bbffea0f'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('70dd2f0c-4757-422a-a5a5-dc4fe8738d42'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7a1da7c9-f6c8-4c0a-985a-30f581e32550'), verbose_name='Slug'),
        ),
    ]
