# Generated by Django 3.2.6 on 2021-08-11 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210811_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('778bc350-c147-4ced-9755-9938be630614'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d16671b4-9b1b-4152-8bc3-e5c8d8fe3f4f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ddbbcf80-4348-4060-8abb-8799ecd2ec2f'), verbose_name='Slug'),
        ),
    ]
