# Generated by Django 3.2.6 on 2021-08-11 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210811_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fb5f570a-0f55-403a-9268-d9a96ba7a8b3'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d5c99de4-1286-47fe-a57b-7e73738f97d5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('372603f6-bc67-4a22-b57f-6cbfd6ed58ad'), verbose_name='Slug'),
        ),
    ]
