# Generated by Django 3.2.6 on 2021-08-11 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210811_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b72c9530-5ce9-48d2-bd34-7066e69d6ac8'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('66974dc5-8723-4cc4-8130-73911afa0d78'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('794997b5-7ca0-4b10-918e-a254cf26e1c0'), verbose_name='Slug'),
        ),
    ]
