# Generated by Django 3.2.6 on 2021-08-11 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210811_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('287ef094-8fba-4221-b865-36b8ef49eb65'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('748ef6c8-9c32-455b-963d-7f35777accc7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('56abffb0-2777-4bf3-b0c2-ea4f3e758477'), verbose_name='Slug'),
        ),
    ]
