# Generated by Django 3.2.6 on 2021-08-11 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210811_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9415caf4-51cc-4447-be0a-a89b1f79d2bf'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f41e5c4d-3111-4624-af64-b2fe5c38aad1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('006fd746-43bf-4473-803d-5f032078ab72'), verbose_name='Slug'),
        ),
    ]
