# Generated by Django 3.2.6 on 2021-08-11 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210811_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('62612f84-6bae-46f1-a635-0fb3f0d50012'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e5949fab-5050-4fae-8684-565f26519756'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1df006a6-5e35-41e6-8b9e-997f5aaf6689'), verbose_name='Slug'),
        ),
    ]
