# Generated by Django 3.2.6 on 2021-08-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210811_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1b97999f-7f1a-4ff3-b61d-43248831e15e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6533e231-d851-4447-8e21-21f64a4934f2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ff023423-6af4-457a-ae55-53f7ce0ff80b'), verbose_name='Slug'),
        ),
    ]
