# Generated by Django 3.2.6 on 2021-08-11 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210811_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e4867acd-1ec4-416e-ba06-1d33e7cb3d2b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4a309852-5d6b-4dd1-a7ea-dcbc07938abb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9ebc205c-89c0-4b92-89fc-f00f1d4636fb'), verbose_name='Slug'),
        ),
    ]
