# Generated by Django 3.2.6 on 2021-08-11 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210811_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c60928cd-a950-4365-9b5d-5db31d2d7476'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ea9e7e37-1ae0-400b-b90f-ba907e8d5b32'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2eab70bd-0828-425f-8380-f0e6df4a0b32'), verbose_name='Slug'),
        ),
    ]
