# Generated by Django 3.2.6 on 2021-08-11 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210811_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1225f116-60ad-400c-b960-cfcf90eaa7ff'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('20e91a51-6d1e-4ea7-a44f-9d2a79376577'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7ceacbd7-05c7-4ea6-820c-e5750790b301'), verbose_name='Slug'),
        ),
    ]
