# Generated by Django 3.2.6 on 2021-08-11 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210811_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8ca505b6-039b-48e0-916a-3ffe9dda97c1'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('16059fc7-0b0b-4ee3-aa89-4eaf7e5bc7bc'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8832b828-803c-473d-b0ee-85e2274c0245'), verbose_name='Slug'),
        ),
    ]
