# Generated by Django 3.2.6 on 2021-08-11 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210811_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2ca3e2d8-2501-4005-91c0-aafb55004c25'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5e4ec7bf-988b-42a0-ae2e-601ed54b8dac'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0d0e075c-8176-4539-a78e-6f3e8780c10c'), verbose_name='Slug'),
        ),
    ]
