# Generated by Django 3.2.6 on 2021-08-11 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210811_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d37b8133-1686-4fde-988c-75173fae7121'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6309fc9c-2d3e-4c41-b96c-4a11f6b9fa96'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0320347a-3962-4c6a-a630-6c4447d2ecfe'), verbose_name='Slug'),
        ),
    ]
