# Generated by Django 3.2.6 on 2021-08-11 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210811_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e13ebbb3-dbc4-4636-b074-7820013dd42a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f31033f0-7fd7-4a1b-a64e-57ef5fb77a09'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5f336729-757a-4ae1-a732-e30cafd5c454'), verbose_name='Slug'),
        ),
    ]
