# Generated by Django 3.2.6 on 2021-08-12 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210812_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('334b829e-ff8b-41a8-b6b0-8f2a1a065ddd'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b7734204-d125-420c-9b0c-8991dad0b4b0'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b7aeda22-d979-4287-96ea-aa9538e00c78'), verbose_name='Slug'),
        ),
    ]
