# Generated by Django 3.2.6 on 2021-08-12 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20210812_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2cadb244-9ad6-4fe2-ba12-c9af81522639'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7a8c4f55-0315-4d02-bc67-7d93f808c80a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('27929dba-24e7-4510-a8eb-b32388ec9ca3'), verbose_name='Slug'),
        ),
    ]
