# Generated by Django 3.2.6 on 2021-08-12 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210812_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('eb80e438-a215-4534-831a-b4d348f9f1a6'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4ba6fd4c-5e4d-4d37-b2d6-b8ff376fffd6'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('76153ab5-648d-457b-bd7c-bdf8ac5a28eb'), verbose_name='Slug'),
        ),
    ]
