# Generated by Django 3.2.6 on 2021-08-12 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210812_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('65d62da4-891f-4907-a0a9-412889e0dd8d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c6841f2b-53d1-497e-a19d-db3295689247'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e224549a-1c59-4958-a8b9-f4c7e2faf1fa'), verbose_name='Slug'),
        ),
    ]
