# Generated by Django 3.2.6 on 2021-08-12 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20210812_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7d75fc25-9856-4bff-a514-3de88f025917'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d4186ba7-e4a4-49e8-ab27-3d14ce1fb347'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='text_to_audio', verbose_name='Audio from text'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8e480ac0-6c0f-4234-b78f-f1a84057a4fc'), verbose_name='Slug'),
        ),
    ]
