# Generated by Django 3.2.6 on 2021-08-12 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210812_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6337887a-838a-435f-9faa-43a8173ec3b1'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('58fb58f6-5151-43b9-9670-fa335f080591'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ed8012dc-62ff-4c88-93c4-cb3417f9b788'), verbose_name='Slug'),
        ),
    ]
