# Generated by Django 3.2.6 on 2021-08-12 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20210812_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f0c06a51-0b44-4efd-8211-96d2b8788931'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('78fd86cb-146d-47ba-8c1a-b47022a7c2b2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9ab80194-3668-43cc-b1f0-72c2bf182216'), verbose_name='Slug'),
        ),
    ]
