# Generated by Django 3.2.6 on 2021-08-12 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210812_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('473f9218-65c6-459e-b83f-48070859dcab'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('268870ab-64ab-4c05-972d-c662e330b5c4'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c6617316-08e0-4897-a0bc-dc940509a068'), verbose_name='Slug'),
        ),
    ]
