# Generated by Django 3.2.6 on 2021-08-12 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20210812_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2218b3e0-e358-43bb-a328-ed27136803ab'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6a155334-21ac-435d-81e7-a72316bc2bf5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e816eabd-ca9b-4161-bf38-288fa83a43a6'), verbose_name='Slug'),
        ),
    ]
