# Generated by Django 3.2.6 on 2021-08-12 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20210812_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8c7d3a22-3541-4976-808d-2003fdac6a43'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('236ffe31-68b7-46c7-b67c-f8ff0b4d6c6d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('203d6e0b-7ff7-46cd-aede-6aa49a54071a'), verbose_name='Slug'),
        ),
    ]
