# Generated by Django 3.2.6 on 2021-08-12 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20210812_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6a979b4f-5233-4877-a5bf-a005fe3ec74b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('390419f7-b47b-44c3-ac70-3705692358b2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('445aee36-7fcb-4470-a84f-7b0d6dd5ccfd'), verbose_name='Slug'),
        ),
    ]
