# Generated by Django 3.2.6 on 2021-08-12 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20210812_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('93a592b1-829f-494d-8191-5ef4567c7b9f'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5b069d1a-8926-4c87-b142-1c0b7a549326'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('74b1702f-06fa-4e2f-8649-247c8fc6e1dc'), verbose_name='Slug'),
        ),
    ]
