# Generated by Django 3.2.6 on 2021-08-12 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20210812_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6dec3d33-9d7e-42b4-8eff-76f2096772fc'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c020caac-ad3f-4aa2-8cb1-191d10477e49'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('441a159e-fd44-4650-912a-8451fdb77ddb'), verbose_name='Slug'),
        ),
    ]
