# Generated by Django 3.2.6 on 2021-08-12 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20210812_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0d68c9ac-a109-48ee-9468-19fc3ced9024'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('61a2e30b-48f9-4f0e-91f9-419dacd35823'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4cf7fdd4-732b-46b4-90f5-9d02dfcb52e2'), verbose_name='Slug'),
        ),
    ]
