# Generated by Django 3.2.6 on 2021-08-12 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20210812_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c0a79193-6da6-4b6d-a648-1588744692a3'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('61736816-c1a8-4d35-95b9-9c750d3a30d6'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e5c36365-4d6e-4074-ae10-e7b1cc430609'), verbose_name='Slug'),
        ),
    ]
