# Generated by Django 3.2.6 on 2021-08-12 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20210812_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f1682cff-7522-4ea3-96b2-6b87610d1a9f'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5299b55a-5770-4e3c-84e5-e35850cd331c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7b72eece-2866-4997-a27a-1f25a99bafb9'), verbose_name='Slug'),
        ),
    ]
