# Generated by Django 3.2.6 on 2021-08-12 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20210812_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('77ee7e23-b2b6-4325-bff9-ca09962cc8d1'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4439b103-84dd-43de-aa79-323c98c0ea08'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1a7b6abb-e540-4880-95e4-365b93561a79'), verbose_name='Slug'),
        ),
    ]
