# Generated by Django 3.2.6 on 2021-08-12 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20210812_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1b33873d-ee72-4f4e-8fea-17e8c336199a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ec2b4519-e0de-45c0-bd43-c54d8e7cfd28'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3983ccd9-9e00-4028-aac9-bff9804699b0'), verbose_name='Slug'),
        ),
    ]
