# Generated by Django 3.2.6 on 2021-08-12 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20210812_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3f4bc20d-295b-47bf-8e89-f4cfcd5bb046'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('218303f1-1774-4452-84e0-2a567c5b7f4f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7149683f-2eb7-4ee5-8cfb-9046b63aaafa'), verbose_name='Slug'),
        ),
    ]
