# Generated by Django 3.2.6 on 2021-08-12 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20210812_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8fc37def-207e-4ba9-a499-24a92a3fd9c6'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('24096150-5d98-44d0-b3f6-de542e4300d3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a564ab16-7197-42e0-948a-6901df6b4724'), verbose_name='Slug'),
        ),
    ]
