# Generated by Django 3.2.6 on 2021-08-12 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20210812_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0368a6fd-7599-4201-84a4-cb7571ad317e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('77edd086-55b8-4ba4-b880-fd027bf6fa1f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4b4e8e1f-6da5-4141-ab7b-ff79bf8e2fa3'), verbose_name='Slug'),
        ),
    ]
