# Generated by Django 3.2.6 on 2021-08-12 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20210812_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1b44b2c2-556d-4675-81cf-355b36febfa4'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a555b8da-c0f8-44a2-b555-e4d9b40f57e7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('942e06fd-530c-4763-83f9-2e5fdefa7da9'), verbose_name='Slug'),
        ),
    ]
