# Generated by Django 3.2.6 on 2021-08-12 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20210812_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('752f39e0-62be-4914-bad8-6738bfcf00b8'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('957dd967-0497-4873-a29c-d5bbb2de7124'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2bec76d0-1013-429c-9215-57e5d9f9dd89'), verbose_name='Slug'),
        ),
    ]
