# Generated by Django 3.2.6 on 2021-08-12 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20210812_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d8213757-7ece-4964-9e87-36f2cc0e3d69'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e2a9d7f4-58ee-47d5-8ea7-41b2211cd2a0'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('64ac16cc-6212-4742-b191-f027bf8751c3'), verbose_name='Slug'),
        ),
    ]
