# Generated by Django 3.2.6 on 2021-08-12 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20210812_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('97d1c9c1-5d10-4f5f-a541-601bfbda10ce'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('acf07374-dee5-46a8-836e-84f6a13d75f2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cf48ed8d-d8dd-4104-9248-332465d8a52a'), verbose_name='Slug'),
        ),
    ]
