# Generated by Django 3.2.6 on 2021-08-12 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20210812_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f29553f6-5808-42f8-a378-4b81930acda4'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('70bba62a-957d-46c0-af24-341aa5f1d46d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a1a15bcc-3614-46a8-a6c2-8c3f0bd696c9'), verbose_name='Slug'),
        ),
    ]
