# Generated by Django 3.2.6 on 2021-08-12 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20210812_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f32fb668-3458-402d-bdab-a5e1027350c0'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('00a77a9e-79a7-4e7f-a610-10b2447fbb3f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f1da3dea-4ad5-4f70-b18f-33004d9dc0cf'), verbose_name='Slug'),
        ),
    ]
