# Generated by Django 3.2.6 on 2021-08-12 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20210812_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0902ef05-38a9-463c-a2ed-c1bf7cd17ca8'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('27e5bb27-1d80-4924-bc05-d61d3679899d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('025d658b-ef43-4dd7-b047-581ea63bfd9d'), verbose_name='Slug'),
        ),
    ]
