# Generated by Django 3.2.6 on 2021-08-12 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20210812_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fd2ddf06-1df9-4afe-8d8a-5f5421e37382'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ac690073-b7f7-41d4-94fe-b9570c0eba84'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7984234a-d079-49e0-80f2-56f0ff7909db'), verbose_name='Slug'),
        ),
    ]
