# Generated by Django 3.2.6 on 2021-08-12 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20210812_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('635b0402-7cde-44ea-a2dc-e8f56798a6b0'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8bc0e4df-2bd3-4163-9100-cc487a902fec'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a651c315-e97c-4c40-912f-2f08369977c5'), verbose_name='Slug'),
        ),
    ]
