# Generated by Django 3.2.6 on 2021-08-12 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20210812_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('952bf591-d04e-452c-a3b7-34803a20cfda'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5df7846a-80d9-4ec5-a59d-ccca05a2cab1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('214e580c-fa97-4bd0-abb5-c449f2cf1c14'), verbose_name='Slug'),
        ),
    ]
