# Generated by Django 3.2.6 on 2021-08-12 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20210812_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a8fc3e88-a7a4-4e30-9c58-d02a9360074e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('47cdf892-70e1-45ac-9048-17422faa4730'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d093d949-dc8e-4bba-9c1b-b83a1c081a72'), verbose_name='Slug'),
        ),
    ]
