# Generated by Django 3.2.6 on 2021-08-12 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20210812_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('102bcba5-890d-49c1-9c2b-32bd6d42cb27'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fb33339c-f52d-4c07-82dc-0ea2ec08d60d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('981aacc8-7a69-4ae0-b147-f739f5f98e67'), verbose_name='Slug'),
        ),
    ]
