# Generated by Django 3.2.6 on 2021-08-12 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20210812_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('84d37650-c0e5-47f3-8c01-19695fd02ac9'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8c745bfa-49fe-4110-bcc3-138af441101e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d1babdfd-8506-4e44-b52a-ae2e957c8551'), verbose_name='Slug'),
        ),
    ]
