# Generated by Django 3.2.6 on 2021-08-12 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20210812_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('64720e11-6f02-40e0-b287-e64400df0549'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0940c006-dcf1-465f-a729-578f671c4bbf'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2f3e556b-37a0-456f-9d84-1179790ba984'), verbose_name='Slug'),
        ),
    ]
