# Generated by Django 3.2.6 on 2021-08-12 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20210812_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('04c55c51-de73-4fbb-8a59-97bc9af70117'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('62545d36-d096-451e-88e5-193f1e1a5475'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f7fe1ad7-723e-4c75-94cf-1bf4727be332'), verbose_name='Slug'),
        ),
    ]
