# Generated by Django 3.2.6 on 2021-08-12 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20210812_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2fffc620-ff4a-453a-976f-8b8c4d0611ca'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('81c268d8-dcb5-4e89-966f-87748b562790'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9a23d5b6-20a0-4887-aa47-f1c5960d7e43'), verbose_name='Slug'),
        ),
    ]
