# Generated by Django 3.2.6 on 2021-08-12 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20210812_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('de7b99e7-f988-41bd-b692-af865718d868'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6bf1d7b8-0b9e-46c9-8d2b-6bd005aa98fb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('41f2d93f-dee5-491a-a479-d22fdcbcaf19'), verbose_name='Slug'),
        ),
    ]
