# Generated by Django 3.2.6 on 2021-08-12 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20210812_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f4cd789b-c94b-4948-9adf-34bdb70ac3aa'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('93618a96-632a-4fa6-b5d1-7804cb727a7a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6958a123-c692-46b4-b731-bdc3d690808c'), verbose_name='Slug'),
        ),
    ]
