# Generated by Django 3.2.6 on 2021-08-12 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20210812_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.UUID('584d083a-662c-44a2-bffa-d7dc832f892f'), verbose_name='Slug')),
                ('audio', models.FileField(upload_to='audio_to_text', verbose_name='Audio')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Audio to text',
                'verbose_name_plural': 'Audios to text',
            },
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e66c6983-c858-48c0-8295-2c1c8f50f77b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('48f06712-3cc1-406d-9eba-8d7f6e71de77'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('abb6f47d-9a58-400f-a299-6208d520418c'), verbose_name='Slug'),
        ),
    ]
