# Generated by Django 3.2.6 on 2021-08-12 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20210812_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('18869d46-b086-45b0-9eb6-154db07a2ae8'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1b72f32a-69aa-42d4-8611-c9eaee399923'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c1749bf9-0fc3-494c-a9f5-b5120d16060a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bf000a8c-0b0f-483b-82e7-adc514bfd08e'), verbose_name='Slug'),
        ),
    ]
