# Generated by Django 3.2.6 on 2021-08-12 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20210812_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('88f43f90-630a-43be-83f2-0f57529fc14f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7e8e98f2-cd1a-4901-9b6a-fdcb9b122327'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4c618ee6-3803-43a2-94fe-ce0fb46d808d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ec16b991-fbe6-4422-8e7a-32908043f67a'), verbose_name='Slug'),
        ),
    ]
