# Generated by Django 3.2.6 on 2021-08-12 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20210812_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('15e1fd69-7f65-4e1f-91f4-abb1487edbf4'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fa047969-4868-4851-b83c-f57f55530622'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e31454a1-57a9-486a-b77a-b7b648605bc9'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fc63daa5-fd00-497f-9ad3-4a5c52688b68'), verbose_name='Slug'),
        ),
    ]
