# Generated by Django 3.2.6 on 2021-08-12 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20210812_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3df8859f-d12a-4bf4-bf6a-6a83ff85e8b3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('030bb130-7e7a-4c2c-a367-4ce1088523ba'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4555ea4f-b9a1-445e-9582-7e646338eb8c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2950f738-c357-4f05-9444-0b483a168c21'), verbose_name='Slug'),
        ),
    ]
