# Generated by Django 3.2.6 on 2021-08-12 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20210812_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('92902744-a0c5-4211-8c83-942fd9b698cd'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('12d746b3-f0a6-420b-9238-08f25b0ec24b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0fef1297-acef-4f8e-b3da-432a750cd10d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c7c94672-139c-4320-bfdf-251989758c96'), verbose_name='Slug'),
        ),
    ]
