# Generated by Django 3.2.6 on 2021-08-12 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20210812_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c255e13d-5518-4739-9586-ef89e5628180'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0b88e7e8-bc64-4ad5-a548-285ce1c38951'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5b8f2351-474f-4bf5-8938-c098a129b8a1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cdff7683-ab0b-4460-84bc-db9b7a6b69de'), verbose_name='Slug'),
        ),
    ]
