# Generated by Django 3.2.6 on 2021-08-12 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20210812_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('afc625d7-75c5-4770-a2e4-d59d278b5fcf'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d50b1df4-4246-44e5-961e-95dc85971617'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e31a38f4-4a68-411b-a759-b6f387eb4f4a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c14505df-33ab-4efb-99b5-353e926e777d'), verbose_name='Slug'),
        ),
    ]
