# Generated by Django 3.2.6 on 2021-08-12 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20210812_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('539df685-767f-4f13-9ee4-6b0913f827aa'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('387734ff-8a8a-494b-8d6e-3ce260319689'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('11eb6892-0816-4cb5-a741-7554130971ed'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9ed1e9bd-36ac-45aa-9700-e8d9aef43956'), verbose_name='Slug'),
        ),
    ]
