# Generated by Django 3.2.6 on 2021-08-12 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20210812_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a2af58ef-ef5b-4ac4-8c92-3dff918f61d3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('beed2d52-a560-43d6-a5b6-71a8a75b7584'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d1080b14-899f-41fb-adbb-8bf7d24fa2dd'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7b369a55-255f-4ab5-8189-901301b0d90a'), verbose_name='Slug'),
        ),
    ]
