# Generated by Django 3.2.6 on 2021-08-12 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20210812_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b07f0d8c-e36e-469b-947f-97960c45f0f0'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('79935a5d-28b9-4676-ab72-0d7e9c25f3cf'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5b474093-a9f5-4ddd-88e5-dd4e727e8f2c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9cc1c35f-5964-4a4c-8dcb-70080760fafe'), verbose_name='Slug'),
        ),
    ]
