# Generated by Django 3.2.6 on 2021-08-13 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20210812_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f7b086a0-5905-4f9b-a00f-0af9c4704da8'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6e82049a-fc9b-4eac-bb36-b87d4062913d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4fa0dfd8-80d7-426f-bad6-10ff2e3b8592'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3a0e7285-7dd8-4891-8d39-aadc2a496723'), verbose_name='Slug'),
        ),
    ]
