# Generated by Django 3.2.6 on 2021-08-13 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20210813_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('925c0da5-fb34-410d-b6de-7b12b88259e5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8b0b8a91-94bd-4f60-b738-44ac86495c5a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('dc52d2a2-aef2-4ed7-9a95-099cd2fa055c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fe25f10a-3f4e-4b00-981b-ec0769b2fea5'), verbose_name='Slug'),
        ),
    ]
