# Generated by Django 3.2.6 on 2021-08-13 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20210813_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9eb96176-8292-4f09-b7ba-6ac0782247d6'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b4685418-e6fa-44f8-81d8-6393d7095818'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b6a44b35-de1e-4120-a392-8e535aba752b'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d2758c18-6324-4f27-8a89-70c305b91b23'), verbose_name='Slug'),
        ),
    ]
