# Generated by Django 3.2.6 on 2021-08-13 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20210813_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('29174ba3-4e28-42ca-977a-c07515a538ec'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3cee8863-5f9a-42df-86a9-bdc237120a8e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4965cf63-83a3-47bd-b82f-0fb636de30b0'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3d4aa82a-1b41-4105-87ae-6273503f31a5'), verbose_name='Slug'),
        ),
    ]
