# Generated by Django 3.2.6 on 2021-08-13 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20210813_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c1b9acbf-f113-4f57-9740-21b6066a60cf'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('be54b16b-b07f-4a97-8f4f-70d4ebb8e4ad'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e88fbdf3-1d7a-45fb-b4ce-76b444d7c644'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7495db2e-6de7-4068-8ae0-71b0f03cfa04'), verbose_name='Slug'),
        ),
    ]
