# Generated by Django 3.2.6 on 2021-08-13 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20210813_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7c319bb5-7c7e-4fb6-95bf-18cf255c094f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bbcfb207-1dbd-4775-a044-6ec57ca569ce'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b46bad48-9d22-4db7-8023-363eecab9233'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('af8d5c3c-4020-46c1-9d2c-e465b5879d88'), verbose_name='Slug'),
        ),
    ]
