# Generated by Django 3.2.6 on 2021-08-13 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_auto_20210813_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2aeba9b8-b329-4644-a583-5cf33f19aa1f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('18593185-5997-4d0f-9956-494dd2ce3e0c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1be5d5a0-f61b-42ca-9bf8-e5b09da64d39'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('002544db-389f-4cb5-a5c2-4bf331e508d9'), verbose_name='Slug'),
        ),
    ]
