# Generated by Django 3.2.6 on 2021-08-13 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20210813_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1a751da2-0886-4e4d-816b-dc965154f419'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('51a6cb40-b9ef-4276-acca-97e2302c0c05'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e7c96344-c4c7-45e9-9911-e509f0540a0d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4d766f81-1577-404f-92aa-894f6ab1b27b'), verbose_name='Slug'),
        ),
    ]
