# Generated by Django 3.2.6 on 2021-08-13 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20210813_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5fc76640-619c-41a9-96f1-f99f9a13ee06'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5569a293-e6ca-4e35-b160-6b6556a3ae37'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f027136e-7831-4d42-99b3-1a3a7de8fea7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aba015c2-0317-4ad3-b417-d4f14e33672d'), verbose_name='Slug'),
        ),
    ]
