# Generated by Django 3.2.6 on 2021-08-13 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20210813_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('58c35a7e-fa03-4251-b939-587c366f3931'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('277a4f00-545a-47ae-8f5e-c2e159766d0c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c2e77de9-4899-4f4b-a6ef-dabc1c9faf29'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('42c7c107-2aaf-49fc-bd4d-75233e9f00d5'), verbose_name='Slug'),
        ),
    ]
