# Generated by Django 3.2.6 on 2021-08-13 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20210813_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1517e40b-7892-4597-9515-7a2e8bc379bf'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c97284a4-0844-485a-973b-2d9247e4863d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7900ef70-ffa9-42cf-9c29-7f1a26928b7d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2dd1102d-dda6-4668-b02f-f717ecdc7b51'), verbose_name='Slug'),
        ),
    ]
