# Generated by Django 3.2.6 on 2021-08-13 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20210813_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9e67bd7e-41b3-405e-bf46-78599d7b77af'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('acdd4a0d-5ed7-4f85-80e5-9446800b2caa'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bab522a7-b104-4a0f-ac93-9e0e4d260b06'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ea59b98b-d57d-4995-a1bd-04a59d1f0152'), verbose_name='Slug'),
        ),
    ]
