# Generated by Django 3.2.6 on 2021-08-13 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20210813_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2a3def42-6a95-459d-a002-ba7cbfff0a0f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8fdbde22-0d10-4cfc-aa0a-90e1c52b4ada'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d1f6d15f-1201-4c4f-9f25-394e1dcd1709'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e2368b87-fbc0-4b96-8d67-02582a968d65'), verbose_name='Slug'),
        ),
    ]
