# Generated by Django 3.2.6 on 2021-08-13 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20210813_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('297391a0-aa8b-4191-b3b7-353ed6a84e4d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d7c8a144-469c-4d7c-b24f-0522afc01b45'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('23f2a894-057b-46af-9a67-ff849cc56f8c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('279107c1-19b6-4fad-af60-64b2997546c4'), verbose_name='Slug'),
        ),
    ]
