# Generated by Django 3.2.6 on 2021-08-13 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20210813_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9c08e49b-f251-4cbe-9abd-3736f00e4000'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('153a5aef-9368-4bc0-b70d-63435950758d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4c931a2f-af67-4c36-85d3-2f49b564f554'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4357d60c-8c5b-4524-8fa7-8536303e7afa'), verbose_name='Slug'),
        ),
    ]
