# Generated by Django 3.2.6 on 2021-08-13 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20210813_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('822a4034-4756-4d89-b76f-34588bfb7316'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1a7610cb-2cab-42cd-be2d-c79ddc98675e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('94657436-2cf9-4743-bed5-a6b026baf7a2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fe233e78-86ea-4fcd-8730-8d4b8b1bfb2c'), verbose_name='Slug'),
        ),
    ]
