# Generated by Django 3.2.6 on 2021-08-13 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20210813_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5000c7dc-289e-4d37-8624-5e5f5d53348a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2a8291a2-efa3-4606-a45c-5bb54dd9bf4a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8986894a-9b7e-4a59-9798-81f3e0ea9d4d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d302a92c-da61-4d74-baae-dd17d55992a3'), verbose_name='Slug'),
        ),
    ]
