# Generated by Django 3.2.6 on 2021-08-13 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20210813_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aa7a68a6-1b7c-4886-a5ca-219d2ba2c478'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8112d568-4685-47be-8475-9d415a73b311'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f25b2640-1a9b-47e5-bf93-28e94f3f5da3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f79d2470-47e6-411a-98d3-790830b51ca1'), verbose_name='Slug'),
        ),
    ]
