# Generated by Django 3.2.6 on 2021-08-13 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20210813_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('72d5c313-e2b4-41b6-bd18-323ff42e7406'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a438ef0a-f8b3-43c4-98de-29f63dec37bc'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('07b40117-54ba-4a93-b541-71911ef21bdd'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('45bc91c8-2d41-49bb-bf14-ae2fbaf0e5c3'), verbose_name='Slug'),
        ),
    ]
