# Generated by Django 3.2.6 on 2021-08-13 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20210813_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ddb36f01-4d33-4be4-bdc2-b395a0b7ca87'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c698d533-0c52-40cc-ae23-d9407eb5292d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c28ba34e-2723-45ca-ae3c-dfba66c77cd9'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d616f327-65cf-4b87-9c7f-f48fea4a8618'), verbose_name='Slug'),
        ),
    ]
