# Generated by Django 3.2.6 on 2021-08-13 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auto_20210813_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aee16c51-4727-46c1-8ae0-d1a4d9cc3862'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('eec3b325-9f1e-4da5-9c2c-07b33b62cdda'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2acdb7ab-7866-49ef-8281-dd07b164b7b8'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1315e04e-9510-4cb1-ae25-8df1d30698fc'), verbose_name='Slug'),
        ),
    ]
