# Generated by Django 3.2.6 on 2021-08-16 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20210813_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1d87b752-452f-44e4-bc98-818de5354304'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('31181095-0a04-43eb-b13a-f26c312236e3'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e3b4dcac-97ed-4da8-ae85-c3053053bcb2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6f9772d6-00f6-4174-b7b5-40f0e0112f59'), verbose_name='Slug'),
        ),
    ]
