# Generated by Django 3.2.6 on 2021-08-16 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20210816_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a0ba5494-0427-4ebc-b59e-47045ed4a9c7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('17b5a9bb-89ad-4b51-a3ca-85abef58c32c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('58f859ce-3484-4083-b318-fc0d866a0bf3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4be10534-3a11-4d25-817b-afcf12f91496'), verbose_name='Slug'),
        ),
    ]
