# Generated by Django 3.2.6 on 2021-08-16 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20210816_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('438bd388-b19d-475e-84cf-6412c75bd2e2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('86d93a30-6eb4-47f1-9141-83cf55956112'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9ed16eac-1941-4969-a871-a7e0edd911df'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bc851176-590e-4a07-80a4-147e6571b2ca'), verbose_name='Slug'),
        ),
    ]
