# Generated by Django 3.2.6 on 2021-08-16 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20210816_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e2d0419f-6d22-4476-841b-163439125298'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('002fdef3-3b7e-4f88-b690-9cb8019bb7c1'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3fc5d4aa-d397-4854-bb3a-fe7629f08a6d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fd784f17-a691-4ae1-99d3-1c04e54e824c'), verbose_name='Slug'),
        ),
    ]
