# Generated by Django 3.2.6 on 2021-08-16 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_auto_20210816_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('25027511-137a-4712-861c-a471f05bc716'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ac04fed8-9a08-430c-8391-22af908cf23e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4241bec5-e031-4251-8bf1-df2d2061faba'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7a6b106b-7b8b-4d77-93b6-e0ffb76d8eb7'), verbose_name='Slug'),
        ),
    ]
