# Generated by Django 3.2.6 on 2021-08-16 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_auto_20210816_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('552617ea-f84c-403b-bde4-17b74ca79900'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c4318c47-f546-488f-9daa-50685724524d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cceb366e-1d73-4202-b4dc-6123e24748bf'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3835cd2e-8ba7-40a7-a820-b2368b9f217d'), verbose_name='Slug'),
        ),
    ]
