# Generated by Django 3.2.6 on 2021-08-16 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20210816_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6c5da7f5-df9a-4814-864b-22b9267cca35'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cdeb52da-639a-4453-8c03-ed389d67de39'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('38bd9e07-c00b-486b-a50b-0645b17263c1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('43de11ce-ca18-4d4c-b26c-86837903952d'), verbose_name='Slug'),
        ),
    ]
