# Generated by Django 3.2.6 on 2021-08-16 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_auto_20210816_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8297bfeb-1c28-478f-9bbc-bf14a23d3bd3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2d934dc2-8954-44ab-8d65-48119d669a82'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e93c3eb0-9101-4f09-b0f4-454f767e6a45'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4ae249b1-fc97-4246-90d0-230f936a5d5c'), verbose_name='Slug'),
        ),
    ]
