# Generated by Django 3.2.6 on 2021-08-16 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20210816_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('44b54b86-8c15-443e-bfb8-9dd8e5ce8dbd'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('713116c9-c3f6-47d5-a858-c03153e611d2'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('eb3c02eb-c136-43b8-b149-5d38d88017fb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('59686dab-7369-4566-ac5f-dacb6dad437b'), verbose_name='Slug'),
        ),
    ]
