# Generated by Django 3.2.6 on 2021-08-16 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_auto_20210816_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e80376e4-9496-4eef-843e-f1ac6fa82eea'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8b4ce466-0e60-419d-a40a-416961d3a02b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a06de7fa-2965-4c36-a899-c4724eade38d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('106dbdad-49aa-4ce0-81a0-a02189cd237b'), verbose_name='Slug'),
        ),
    ]
