# Generated by Django 3.2.6 on 2021-08-16 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_auto_20210816_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7dbf472c-82d7-4ad1-8a1e-5858cbd3016c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ce554cb1-3f30-4c71-90f5-41bb5b0c1f70'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0f7f948b-0357-4c78-b904-c32d94cf9f10'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('eed4ab2b-e7d4-4f63-85a4-2cfb7a7c8338'), verbose_name='Slug'),
        ),
    ]
