# Generated by Django 3.2.6 on 2021-08-17 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_auto_20210816_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1f55738e-0222-40e1-85f9-cf054ba62f98'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d2cc3e77-0ee8-4c45-9980-f8df5c39ccfc'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('20621017-c311-4d95-a547-c4e6569d155b'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('27aa90fd-f34e-48ad-a2d3-ae0ef648444d'), verbose_name='Slug'),
        ),
    ]
