# Generated by Django 3.2.6 on 2021-08-17 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20210817_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a5f28f2b-a46c-40ca-95c8-03eca7465d47'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('97edc9ef-8fc0-4571-a34c-b0501e26e64b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3ddbfa2e-c521-44c1-b6d0-90a94837acc7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c48729ed-56ca-469b-be67-8539b8cfa7ea'), verbose_name='Slug'),
        ),
    ]
