# Generated by Django 3.2.6 on 2021-08-17 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_auto_20210817_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c7ac4c5f-c2d2-4349-8d73-321542604ef1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('11285e9b-42d8-4f8e-bf72-41390e6b3a95'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('dc8e0b64-dc80-477d-aec3-7bc7a9b984aa'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('648f6bf7-2668-40c2-b422-67c49fa4343e'), verbose_name='Slug'),
        ),
    ]
