# Generated by Django 3.2.6 on 2021-08-17 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_auto_20210817_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('359225bc-fffb-4e77-b17c-1eced673454d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ada95ce4-9a55-4595-b1fa-3c214ea3cab3'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7529e337-f299-454d-b20c-6af375b11387'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('177cf2de-9afa-430f-8255-9597b2a65178'), verbose_name='Slug'),
        ),
    ]
