# Generated by Django 3.2.6 on 2021-08-17 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20210817_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d4a1332c-4dcd-40cb-ae25-64372f3448d2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d64a20d8-41c2-4c9a-a1d8-0d1aca3aa56e'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c9307c45-474c-4e11-b646-59bce61e76de'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c6dc24c9-28a7-4717-b7fb-ad92a3f46151'), verbose_name='Slug'),
        ),
    ]
