# Generated by Django 3.2.6 on 2021-08-17 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_auto_20210817_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1a91cd7f-27ef-4e73-850c-eb03fa44996a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d0cde2d0-2506-4eb4-a08c-edeb5a62637f'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ee970910-f4e4-4e07-a019-8d9438c06bfe'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('66b32bdd-204c-476d-b135-ae4eba0787b4'), verbose_name='Slug'),
        ),
    ]
