# Generated by Django 3.2.6 on 2021-08-17 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_auto_20210817_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('760f9d40-3a3e-42f2-b199-3880bff4032b'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9f954de1-7a59-4f41-903a-f9f34c8278d9'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('73954767-502c-4c93-8559-f5aa4b262b32'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('46a9e830-6af7-4d34-b5c4-376a105815ed'), verbose_name='Slug'),
        ),
    ]
