# Generated by Django 3.2.6 on 2021-08-17 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_auto_20210817_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a0a0079b-9e2f-4385-95ea-a3472528c0f6'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9907762e-47f6-4ea7-be17-1eaf489465e6'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3f31143f-b231-41cc-be1a-7a235f6b7fd7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3a7f974e-5c27-45f5-88ea-0be79d802124'), verbose_name='Slug'),
        ),
    ]
