# Generated by Django 3.2.6 on 2021-08-17 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_auto_20210817_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c08e57a8-8e2f-4401-a4cd-ed11946ce86a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('422fc21f-ca08-45dd-95cd-131d64c3dd4a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c35ac919-dd46-430a-961c-74b526b4bdd7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5cbe8887-6665-446e-bf21-b8ef44e3c816'), verbose_name='Slug'),
        ),
    ]
