# Generated by Django 3.2.6 on 2021-08-17 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_auto_20210817_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ae726547-89dd-46f0-956c-43ef5c96b238'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b65b2e39-3d89-4446-8f64-d073a74f46a0'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b77ec0a8-5f5c-4e03-b81e-36a4ceaca875'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d332585b-2fdc-42fa-be17-1720de6ea49d'), verbose_name='Slug'),
        ),
    ]
