# Generated by Django 3.2.6 on 2021-08-18 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20210818_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6782bc88-ac15-446a-943e-4b607476fcb5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bbdd9066-0a26-4296-a4bd-8b96faff439c'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('98c1bca1-4a76-40ce-89b9-539f6b94521a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3ba1dcdd-7ca9-4241-a275-ab1ff7c3aa6f'), verbose_name='Slug'),
        ),
    ]
