# Generated by Django 3.2.6 on 2021-08-18 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20210818_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3e8cda68-a74c-4f4f-bf50-5f5bb56769cc'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d8402d9b-8f06-439f-aa00-ab694710102b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('392ab644-8b9d-4199-b676-8513fa7ff3a3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e0bd9e69-71c3-4a32-828f-14d0875bfb4c'), verbose_name='Slug'),
        ),
    ]
