# Generated by Django 3.2.6 on 2021-08-18 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20210818_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c2159728-d8a2-42ea-87cb-a621d5f60086'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f14c073e-1f27-41c8-9c5f-478b9e250b08'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('06bc474b-10f4-4dfa-ae15-80b59364392b'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fabb93bc-76ff-4f5b-b677-3b59d5c13280'), verbose_name='Slug'),
        ),
    ]
