# Generated by Django 3.2.6 on 2021-08-18 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_auto_20210818_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('da0ecbaf-2c28-4260-b15f-2c079fffb03b'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4b5aaec0-da4a-4a11-94f6-f781bf1eb14a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bc06de79-c865-47d8-8bd6-94beb601bbeb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0c1300f5-79c9-4ff6-8932-21f154c54995'), verbose_name='Slug'),
        ),
    ]
