# Generated by Django 3.2.6 on 2021-08-18 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20210818_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6efd1dab-d232-4383-b985-7e2e3f6d68e7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('43464558-3e1c-48f2-8f82-63022b0b9f50'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('385a462f-585b-4f80-a808-9712c9388ecb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b80e78c2-aec9-4576-8303-c25acc18ca04'), verbose_name='Slug'),
        ),
    ]
