# Generated by Django 3.2.6 on 2021-08-18 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_auto_20210818_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1d7addf7-e479-4483-8a5f-7024f5358bb3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('27ba13ff-876a-4c92-b205-44fce8143425'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e651e686-d3df-450d-b03e-ac052b8e6df5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bf99da4b-4bf8-4241-bc48-eb0ab9b9ee27'), verbose_name='Slug'),
        ),
    ]
