# Generated by Django 3.2.6 on 2021-08-18 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20210818_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3bbf9880-40a3-4421-99e5-29ae501422ce'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5eb1f186-8f02-4343-bdba-80cc226a60dd'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('eb2498bb-2652-47ba-a766-3198aa15d14d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('102f164b-ca21-4449-8451-76192b45dd88'), verbose_name='Slug'),
        ),
    ]
