# Generated by Django 3.2.6 on 2021-08-18 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_auto_20210818_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('462d20f3-8498-42d0-b330-9e74e6ea2b50'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8821e43e-3e7e-46a4-820b-42bd4e820782'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('54b09eec-60e6-4f36-ac9f-3ad1b4731bf1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('90c0e0fd-edda-470d-81ad-a093178ffb24'), verbose_name='Slug'),
        ),
    ]
