# Generated by Django 3.2.6 on 2021-08-18 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_auto_20210818_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5454acdc-743e-49ed-ad0a-ba268a7ee2c0'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fc7232d3-5368-4490-b93e-72f7426ca23b'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2608f0b4-8c1a-4159-8e97-e9e1001e017e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('126b88b6-5eab-4940-9096-81eaca19fafc'), verbose_name='Slug'),
        ),
    ]
