# Generated by Django 3.2.6 on 2021-08-18 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_auto_20210818_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6072576f-9805-4b92-b673-7afa0c3803c2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('481c90f7-ff9c-4242-b339-c09d01100988'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('90d8591a-2f3d-4910-b0e3-68485e634763'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d25caa85-5163-4bf4-9676-d10b889d2b58'), verbose_name='Slug'),
        ),
    ]
