# Generated by Django 3.2.6 on 2021-08-19 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_auto_20210818_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bea7805f-a14b-4a6c-a5db-63983c9c27da'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('eaf6c04f-ae7c-447e-85f0-cdab2bee6cd2'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bb12dd81-5639-40b2-90ea-63cadb41ac29'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d3f4bd9b-3ab0-42cb-99bb-a3e894d656bf'), verbose_name='Slug'),
        ),
    ]
