# Generated by Django 3.2.6 on 2021-08-24 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_auto_20210819_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.UUID('c71ffe69-8622-4b57-b1b6-9ebf9a5f9a87'), verbose_name='Slug')),
                ('image', models.ImageField(upload_to='images_to_translate', verbose_name='Image')),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Image to audio',
                'verbose_name_plural': 'Images to audio',
            },
        ),
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a7435ba3-d577-41fc-bbb0-48487475a67c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('168fadec-7084-4673-bbd3-d0de7afb0046'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a3a7ab75-3f86-4684-8db6-053ca63b2f7c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('971e386b-e6a0-4854-a37c-aec686d971ff'), verbose_name='Slug'),
        ),
    ]
