# Generated by Django 3.2.6 on 2021-08-24 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_auto_20210824_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2243321f-87cd-4734-886f-0369ce98ad50'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2094cb77-721a-4ea6-ac29-ff3738568244'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5266665d-c987-49bb-9c64-833b24e7b46f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5e67592a-4f11-4049-9a0b-1ccc91513ac6'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f1162de1-356e-48a8-9dcb-4b76df18e55d'), verbose_name='Slug'),
        ),
    ]
