# Generated by Django 3.2.6 on 2021-08-24 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_auto_20210824_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('07aa6d8c-deec-4154-bdd6-83508143b148'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a2e86bff-d966-49b3-af69-374eaa7982fa'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('920d1380-046b-47a7-9ba8-339915e75c8c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bb8f75ec-a49a-4635-9f64-6331dd328381'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('eb10934b-171e-4a7e-ae0b-58c120cdb808'), verbose_name='Slug'),
        ),
    ]
