# Generated by Django 3.2.6 on 2021-08-24 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_auto_20210824_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('29ff8ada-d8a4-413b-a9c6-942cb0f232dd'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e5f2de59-f3cc-494f-9370-998ff7845026'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ddd93de8-de4b-45d6-9fdd-344e07b73e1f'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('36ad0df1-5ed9-46d1-8109-0b7250791983'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9fd6f968-5c96-43e1-8f68-7216187c1fcf'), verbose_name='Slug'),
        ),
    ]
