# Generated by Django 3.2.6 on 2021-08-24 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_auto_20210824_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c8abe33d-0b46-4f53-bb0c-e473144df8f4'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cab3c660-da2c-432c-a1a5-8352bd95fe59'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d5c21541-85a7-4f7a-aa24-ccab7dcc5ff5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('91eb7d68-51da-4690-b5e4-e4eaf43ceffb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9b2ce06f-3651-4376-8742-e59c3c0906db'), verbose_name='Slug'),
        ),
    ]
