# Generated by Django 3.2.6 on 2021-08-24 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20210824_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('30c49355-e85f-45e1-927a-babd1a523122'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d44703da-2a6d-4bb5-94ef-99e4d2948c69'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8b7aa8e8-92e9-4bac-a05d-237abbd994fc'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('021a2325-c2e4-42d1-95bc-83a9940e4a7e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d7ce6802-2cfc-45f2-aec7-7513dd0cf035'), verbose_name='Slug'),
        ),
    ]
