# Generated by Django 3.2.6 on 2021-08-24 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_auto_20210824_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7e70db76-e9be-4dc5-803a-7dfc43412c50'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('51b39eaf-ea23-4128-ac09-940f1f8f7a3d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('691701df-5da0-455d-bbd3-b1a82d064079'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4c34fe25-27f2-4560-82aa-472530fded0e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c8a8973b-cb85-4357-893c-331462f0faf0'), verbose_name='Slug'),
        ),
    ]
