# Generated by Django 3.2.6 on 2021-08-25 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_auto_20210824_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d1042498-1aa6-403e-bac3-ceaf5be5502d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('41e4e605-8c6b-4b1d-87a7-e5ab97409861'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ab86b1f3-1b37-4ef5-839b-bb92250dadae'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e7df411d-9b2e-4cbe-bb48-eb79dfae4bcf'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a15792e6-cd10-491b-ac69-b52388073782'), verbose_name='Slug'),
        ),
    ]
