# Generated by Django 3.2.6 on 2021-08-25 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_auto_20210825_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2c85d420-dc69-4b8c-a341-e18e6a9c1078'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f9a137d7-cadc-4415-8d65-46cdf315620d'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f4a74a2b-f7a0-41e6-aafa-65064e91bc93'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('45ff27ff-e775-4dfb-a089-b593b280e0c3'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5b55779e-0fb7-47b9-9892-f4905967799b'), verbose_name='Slug'),
        ),
    ]
