# Generated by Django 3.2.6 on 2021-08-25 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_auto_20210825_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a3836888-7e87-40f7-9dd9-6b66333dc41c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2082a697-bb43-4ea6-aa42-670f4edd2e81'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f0b065f8-a83f-4844-85b7-196e27105c2e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8fa077f1-d6fd-4d6b-8309-674b08aca3e1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f88a8a90-6344-4ae2-8520-4adb1796dab7'), verbose_name='Slug'),
        ),
    ]
