# Generated by Django 3.2.6 on 2021-08-27 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_auto_20210825_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4f853c39-f336-47c3-9412-a2a847c69414'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0122e7f8-184e-49c1-990c-5473a8bb2ce0'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c1981deb-24d1-494f-a999-993091cb8f2e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('584caf74-532d-43f0-9649-e37b5bc7a4f9'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9601b0b3-1cf7-453c-bd88-f4b80c784229'), verbose_name='Slug'),
        ),
    ]
