# Generated by Django 3.2.6 on 2021-08-28 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_auto_20210827_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToGcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.UUID('510c4fa3-1102-45a1-8a9c-d7ce0506f300'), verbose_name='Slug')),
                ('gcode', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Text to convert',
                'verbose_name_plural': 'Texts to convert',
            },
        ),
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e9a9f3b3-2aca-4888-bd99-69d0462f017d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2f4acccf-ce73-4d46-9ac7-ec4ec7641cc2'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2a362bb1-3852-4490-8338-8a04f66cc068'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0109dbe5-1985-431f-8973-cbf0b2bbd2bb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7c2ab56f-0282-4c20-8a92-727ae8d2dec1'), verbose_name='Slug'),
        ),
    ]
