# Generated by Django 3.2.6 on 2021-08-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_auto_20210828_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('eb68bb5f-e4e0-43fb-b7fe-3a9ae7235a23'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4c004914-50fa-4cd8-833c-9f22316319d1'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('96a93604-86b5-4a2a-8179-faea5976e839'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('1a222bd6-5820-4e9f-9a46-a2f5b8e35103'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ce6362a8-8170-4322-9423-e3d83172b24e'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ba1281a1-7633-4ef3-9821-a8a232f8918e'), verbose_name='Slug'),
        ),
    ]
