# Generated by Django 3.2.6 on 2021-08-28 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_auto_20210828_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('64058b6a-7560-4624-8f8c-8ba2d5f20340'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0f03f6a8-bc2b-4c83-b3e3-e5039a298182'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3dca094f-5668-4a98-bc62-f0971c2445d6'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('868c0c8c-8c23-4e65-ac74-94b0ee692452'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ccbe498d-14e3-49aa-be5a-1469c601dade'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f055ff13-d360-48a3-8611-4cb648dcbafc'), verbose_name='Slug'),
        ),
    ]
