# Generated by Django 3.2.6 on 2021-08-28 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_auto_20210828_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aff9130e-83bc-471d-ba12-03890dec4c99'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0bac28b4-b8d5-4aeb-8ec8-41da14467361'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c028771b-013f-472c-b3a9-c581e0249304'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('59c7ff06-5d9f-402a-a43d-e8d4f97116ca'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ae7a14af-4fe2-464a-8b69-17a779ec7730'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('44b764d3-626c-4ad2-a9c5-028ad55b611c'), verbose_name='Slug'),
        ),
    ]
