# Generated by Django 3.2.6 on 2021-08-28 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_auto_20210828_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('67559084-0c7c-497a-9953-9f4d7655d83a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ff62323a-ce1a-459b-b9f8-4f367a321cb2'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ea57af97-64c7-4828-b848-45ee4afc0505'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0a724f4c-a08e-46ee-b28f-f71714e0116d'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f1736b75-f6e4-4011-a310-84911f0696ff'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0a9e06fa-b74e-4e89-9d5f-d9c55b99e060'), verbose_name='Slug'),
        ),
    ]
