# Generated by Django 3.2.6 on 2021-08-28 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_auto_20210828_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('951f26c2-d8d7-4a9b-9478-07ee4a13ea99'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b4ad7872-7431-4930-8a10-a2d6cc0b144a'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f242fe42-a275-4933-badb-eabbfa8ae301'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b82b1035-e3da-4f42-996c-e52e2986cd14'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('db89e745-92ad-4acc-9b83-4d1378f52f59'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9d508e1c-f0fa-4a2b-b05e-249771814934'), verbose_name='Slug'),
        ),
    ]
