# Generated by Django 3.2.6 on 2021-08-28 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_auto_20210828_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fa410660-e59e-42e9-9102-3b53e81693d8'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ffebbe98-2126-44cf-a939-45889e72f3d1'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('85d88572-e26a-4803-89cf-0976743cba47'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c5945da8-437c-4540-b6a2-ce7bab14bbfd'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f825f3d2-987e-4af2-936e-2a9c434aba65'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cf1ccfc7-59a5-493e-ac27-35a51a5f695b'), verbose_name='Slug'),
        ),
    ]
