# Generated by Django 3.2.6 on 2021-08-28 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_auto_20210828_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a2aebee2-4ce0-4cad-a199-51b4c9894f2c'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('01cc9a43-c7d8-4913-9024-4a811cd9fcfd'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('44937168-2364-48c8-a90c-01c1d1e51b48'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('dd94aea4-3265-411d-b0d3-8d7864219977'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b2830c61-324f-4de4-9d2a-12ad34e7600a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7abc0f69-7f94-4c8e-ab4f-02f5e3338b27'), verbose_name='Slug'),
        ),
    ]
