# Generated by Django 3.2.6 on 2021-08-28 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_auto_20210828_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('469e9f37-7dcf-453a-abf7-bdf6799988f2'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c2178f3b-8fee-4e87-b568-358a6916d509'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c466f642-1914-4673-ab91-d5223f6faaee'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bc093d5f-8d69-4996-9172-961f1d8e45fe'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a24eaac1-336c-4883-b2ec-3d151f0213b7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e89217be-ee53-4564-ae1e-c569920639ff'), verbose_name='Slug'),
        ),
    ]
