# Generated by Django 3.2.6 on 2021-08-28 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20210828_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7007c14d-ab9b-4b0c-87e6-0860c822e5b1'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b44defcd-01d8-4a87-b280-711753474ea0'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('418acc74-e76e-4cfc-b273-8cd0b3f332e7'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('997515d8-1bed-40f6-be46-aae2b8633aa5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('349a62e2-d8f2-4f8c-996e-103b4fef264a'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8a4af832-b51a-473e-83ab-c4b2fdf8566e'), verbose_name='Slug'),
        ),
    ]
