# Generated by Django 3.2.6 on 2021-08-28 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_auto_20210828_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiototext',
            name='slug',
            field=models.SlugField(default=uuid.UUID('03adc42f-bcf6-48b2-866a-d9504398c1ee'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1ae3db63-39d6-4dc2-b779-f9732d21a155'), null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ae44aa09-5d1b-4d5c-9a77-daa5a9c40cad'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imagetotranslate',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7007392a-1b1e-4785-9d61-72ed7af0b0a8'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttoaudio',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cfd33043-fb6c-4b4e-b239-8fcbb9804f84'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='texttogcode',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e0055116-773f-4bbb-9bab-1d0cb4c7ab27'), verbose_name='Slug'),
        ),
    ]
